type: robot_local_control_components/NavigationComponent
desired_freq: 1.0

check_sensors_security: false

#components: [GoToComponent,GoToComponentOther,ChargeComponent,UnchargeComponent,PickComponent,PlaceComponent,EnterShowerComponent,LeaveShowerComponent]
components:
 - GoToComponent
 - PickComponent
 - PlaceComponent
 - ChargeComponent
 - UnchargeComponent

GoToComponent:
  type: robot_local_control_procedures/GoToMoveBase
  desired_freq: 5.0
  action_namespace: move_base
  global_frame: rbkairos_a_map
  base_frame: rbkairos_a_base_footprint
  default_yaw_tolerance: 0.1 # when goal has orientation. if orientation is invalid, goal tolerance is changed to 3.14

PickComponent:
  type: robot_local_control_procedures/Pick
  desired_freq: 1.0
  docker_namespace: cart_docker
  move_namespace: move
  elevator_namespace: robotnik_base_control/set_elevator
  step_in_distance: 0.71
  dock_offset_x: -0.25
  dock_frame: rb2_cart
  robot_dock_frame: rb2_picking_contact_link
  generic_dock_frame_: ".*cart.*"
  has_laser_security: true
  max_y_deviation_for_generic_dock_frame: 0.2
  max_theta_deviation_for_generic_dock_frame: 0.3

PlaceComponent:
  type: robot_local_control_procedures/Place
  desired_freq: 1.0
  move_namespace: move
  elevator_namespace: robotnik_base_control/set_elevator
  step_out_distance: -1.2
  rotation: 0.0
  has_laser_security: true

ChargeComponent:
  type: robot_local_control_procedures/Charge
  desired_freq: 1.0
  docker_namespace: docker
  dock_frame: rbkairos_a_docking_station_contact
  robot_dock_frame: rbkairos_a_front_rgbd_camera_link
  move_namespace: move
  has_laser_security: false
  wait_for_ack: true # now it is being used as a flag to enable charging on rb2
  # todo: offset should come here

UnchargeComponent:
  type: robot_local_control_procedures/Uncharge
  desired_freq: 1.0
  move_namespace: move
  step_back_distance: 0.6
  rotation: 3.14

