<?xml version="1.0"?>
<robot name="tf" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:macro name="leg" params="prefix parent length offset_x offset_y offset_z">
        <link name="${prefix}_leg">
            <visual>
                <geometry>
                    <box size="${leg_width} ${leg_width} ${length}"/>
                </geometry>
                <origin xyz="0 0 -${length/2}" rpy="0 0 0"/>
                <material name="aluminium">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${leg_width} ${leg_width} ${length}"/>
                </geometry>
                <origin xyz="0 0 -${length/2}" rpy="0 0 0"/>
            </collision>
        </link>

        <joint name="base_to_${prefix}_leg" type="fixed">
            <parent link="${parent}"/>
            <child link="${prefix}_leg"/>
            <origin xyz="${offset_x} ${offset_y} ${length/2.0-offset_z}" />
        </joint>

    </xacro:macro>

    <xacro:macro name="truck_frame" params="prefix">

        <xacro:property name="leg_width" value="0.08" />
        <xacro:property name="leg_length_front" value="0.74" />
        <xacro:property name="leg_length_rear" value="0.82" />
        <xacro:property name="pi" value="3.1415926535897931" />
        <xacro:property name="leg_spread_front" value="1.2" />
        <xacro:property name="leg_spread_rear" value="0.85" />
        <xacro:property name="leg_offset_rear" value="1.72" />
        <xacro:property name="leg_offset_front" value="3.27" />
        <xacro:property name="leg_offset_top" value="0.25" />

        <link name="${prefix}truck_frame">
            <visual>
                <origin xyz="0 0 0" rpy="${pi} 0 0" />
                <geometry>
                    <mesh filename="package://truck_frame_support/meshes/visual/truck_frame.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="black">
                    <color rgba="0.2 0.2 0.2 1"/>
                </material>
            </visual>   
            <collision>
                <origin xyz="0 0 0" rpy="${pi} 0 0" />
                <geometry>
                    <mesh filename="package://truck_frame_support/meshes/collision/truck_frame.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>

        <xacro:leg prefix="${prefix}truck_frame_front_left" 
            parent="${prefix}truck_frame" 
            length="${leg_length_front}" 
            offset_x="${leg_offset_front}" 
            offset_y="${leg_spread_front/2}" 
            offset_z="${leg_offset_top-leg_length_rear+leg_length_front}"/>

        <xacro:leg prefix="${prefix}truck_frame_front_right" 
            parent="${prefix}truck_frame" 
            length="${leg_length_front}"
            offset_x="${leg_offset_front}"
            offset_y="${-leg_spread_front/2}" 
            offset_z="${leg_offset_top-leg_length_rear+leg_length_front}"/>

        <xacro:leg prefix="${prefix}truck_frame_rear_left" 
            parent="${prefix}truck_frame" 
            length="${leg_length_rear}" 
            offset_x="${-leg_offset_rear}"
            offset_y="${leg_spread_rear/2}"  
            offset_z="${leg_offset_top}"/>

        <xacro:leg prefix="${prefix}truck_frame_rear_right" 
            parent="${prefix}truck_frame" 
            length="${leg_length_rear}" 
            offset_x="${-leg_offset_rear}" 
            offset_y="${-leg_spread_rear/2}" 
            offset_z="${leg_offset_top}"/>

    </xacro:macro>
    <xacro:truck_frame prefix=""/>
</robot>