#include <ros/ros.h>
#include <image_transport/image_transport.h>
#include <cv_bridge/cv_bridge.h>
#include <sensor_msgs/image_encodings.h>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/video/background_segm.hpp>


cv::Mat frame; //current frame
cv::Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
cv::Ptr<cv::BackgroundSubtractorMOG2> pMOG2; //MOG2 Background subtractor

static const std::string OPENCV_WINDOW = "Image window";

bool savedIMG = 1;
cv::Mat img, foregroundMask, backgroundImage, foregroundImg;

class ImageConverter
{
  ros::NodeHandle nh_;
  image_transport::ImageTransport it_;
  image_transport::Subscriber image_sub_;
  image_transport::Publisher image_pub_;

public:
  ImageConverter()
    : it_(nh_)
  {
    // Subscrive to input video feed and publish output video feed
    image_sub_ = it_.subscribe("/camera/color/image_raw", 1,
      &ImageConverter::imageCb, this);
    image_pub_ = it_.advertise("/image_converter/output_video", 1);
    pMOG2 = cv::createBackgroundSubtractorMOG2();
    pMOG2->setVarThreshold(100);
    pMOG2->setDetectShadows(0);
    cv::namedWindow(OPENCV_WINDOW);
    img = cv::imread("/home/danilo/test2.jpg", cv::IMREAD_COLOR);
    backgroundImage = cv::imread("/home/danilo/test.jpg", cv::IMREAD_COLOR);
    //cv::subtract(backgroundImage,img,foregroundImg);
    //cv::imwrite("test3.jpg", foregroundImg);
    pMOG2->apply(backgroundImage, fgMaskMOG2);
    pMOG2->apply(img, fgMaskMOG2);
    cv::imwrite("test5MASK.jpg", fgMaskMOG2);
    //SHADOW DETECTION!!!

  } 

  ~ImageConverter()
  {
    cv::destroyWindow(OPENCV_WINDOW);
  }

  void imageCb(const sensor_msgs::ImageConstPtr& msg)
  {
    cv_bridge::CvImagePtr cv_ptr;
    try
    {
      cv_ptr = cv_bridge::toCvCopy(msg, sensor_msgs::image_encodings::BGR8);
    }
    catch (cv_bridge::Exception& e)
    {
      ROS_ERROR("cv_bridge exception: %s", e.what());
      return;
    }
    if (savedIMG == 0){
        cv::imwrite("test2.jpg", cv_ptr->image);
        savedIMG = 1;
    }
    
    // Draw an example circle on the video stream
    //if (cv_ptr->image.rows > 60 && cv_ptr->image.cols > 60)
    //  cv::circle(cv_ptr->image, cv::Point(50, 50), 10, CV_RGB(255,0,0));

    // Update GUI Window
    //cv::imshow(OPENCV_WINDOW, cv_ptr->image);
    cv::imshow(OPENCV_WINDOW, fgMaskMOG2);
    cv::waitKey(3);

    // Output modified video stream
    image_pub_.publish(cv_ptr->toImageMsg());
  }
};

int main(int argc, char** argv)
{
  ros::init(argc, argv, "image_converter");
  ImageConverter ic;
  ros::spin();
  return 0;
}
